name: worckflow for node using Snyk
on: push
jobs:
  security-check-snyk:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@master
      -name: Run Snyk to check for vulnerabilities
       uses: snyk/actions/node@master
       continue-on-erroe: true
       env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       with:
         args: --severity-threshold=high
  node-js-code-scan:
    needs: security-checksnyk
    runs-on: ubuntu-latest
    name: njsscan code scanning
    steps:
      -name: checkout th code
       uses: actions/checkout@v2
      -name: nodejsscan scan
       id: njsscan
       uses: zegdane1998/njsscan
       with:
         args: ". --sarif --output results.sarif || true"
      -name: Upload njsscan repot
       uses: github/codeql-action/upload-sarif@v1
       with:
         sarif_file: results.sarif
  port-checker:
    needs: node-js-code-scan
    runs-on: ubuntu-latest
    name: port Scanner + SSL QL Check
    steps:
      -name: Checkout the code
       uses: actions/checkout@v2
       
      -name: setup Golang
       uses: actions/setup-go@v2
       with:
         go-version: "^1.13.1"
      -name: run port Scanner
       run: |
         sudo apt-get install nmap
         nmap www.volue.com > logs.txt
      -mane: SSL Quality Checker
       run: |
         git clone https://github.com/ssllabs/ssllabs-scan.git
         go run ./ssllabs-scan/ssllabs-scan-v3.go www.volue.com >> logs.txt
      -name: upload artifact
       uses: actions/upload-artifact@v2
       with:
         name: SSL QL JSON
         path: ./logs.txt
         
