name: worckflow for node using Snyk
on: push
jobs:
  security-check-snyk:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@master
      -name: Run Snyk to check for vulnerabilities
       continue-on-erroe: true
       env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

         
